# github workflow to automate builds
name: index.json updater

# Controls when the action will run.
on:
  # every hour
  schedule:
  - cron: '0 0-23 * * *'

  # manual
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      #with:
      #  token: ${{ secrets.GITHUB_TOKEN }}
    # overwrite current file if newer and commit
    - name: Main
      env:
        INFO_JSON_URL: ${{ secrets.INFO_JSON_URL }}
        USER_MAIL: ${{ secrets.USER_MAIL }}
        USER_NAME: ${{ secrets.USER_NAME }}
      run: |
        wget -q --timestamp $INFO_JSON_URL
        git config --global user.email "$USER_MAIL"
        git config --global user.name "$INPUT_USER_NAME"
        git add index.json
        git commit -m "updated list"
        git push
