# github workflow to automate builds
name: index.json updater

# Controls when the action will run.
on:
  # every hour
  schedule:
  - cron: '0 0-23 * * *'

  # manual
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        json_url: ${{ secrets.INFO_JSON_URL }}
        user_mail: ${{ secrets.USER_MAIL }}
        user_name: ${{ secrets.USER_NAME }}
        
    # overwrite current file if newer and commit
    - name: Main
      run: |
        wget -q --timestamp $INPUT_JSON_URL
        git config --global user.email "$INPUT_USER_MAIL"
        git config --global user.name "$INPUT_USER_NAME"
        git add index.json
        git commit -m "updated list"
        git push
